services:
  - type: web
    name: job-tracker-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host=0.0.0.0 --port=8000

